#!/usr/bin/python
import string
from operator import xor
ip = raw_input('Enter IP: ')
a = ip.split('.')
#b = hex(int(a[0])) + hex(int(a[1])) + hex(int(a[2])) + hex(int(a[3]))
for i in a:
	b = hex(int(i))
	b = b.replace("0x","")
	print b 
#b = b.replace('0x', '')
#b = b.upper()
#print b
